spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/mydb?currentSchema=project_demo_jpa
    username: user
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false

server:
  port: 8085

email:
  sender: demo.project@example.com